stages:
  - build
  - publish

variables:
  PACKAGE_REGISTRY: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_REF_NAME}"
  JAR_FILE: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.jar"

build:
  stage: build
  only:
    - tags
  image: maven:3.8-jdk-11
  script:
    - echo "Building artifacts"
    - mvn clean install
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file target/${JAR_FILE} ${PACKAGE_REGISTRY}/${JAR_FILE}'
  artifacts:
    paths:
      - "target/${JAR_FILE}"

publish:
  stage: publish
  only:
    - tags
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  dependencies:
    - build
  script:
    - echo "Publishing artifacts"
  release:
    name: "v${CI_COMMIT_TAG}"
    description: "Release candidate v${CI_COMMIT_TAG}"
    tag_name: "${CI_COMMIT_TAG}"
    ref: "${CI_COMMIT_TAG}"
    assets:
      links:
        - name: "${JAR_FILE}"
          url: "${PACKAGE_REGISTRY}/${JAR_FILE}"
